### ISSUE TITLE
Error while runing demo.py on colab

### ISSUE THREAD

**Issue by swapna2205** [Haoran-S/SPAWC2017#1]
i disabled tensor2.0 also but i am getting the following error

Gaussian IC Case: K=10, Total Samples: 25000, Total Iterations: 100

Generate Data ... (seed = 0)
train DNN ...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/content/demo.py in <module>()
     39 # Save & Load model from this path
     40 model_location = "model_10.ckpt"
---> 41 df.train(Xtrain, Ytrain, model_location, training_epochs=training_epochs, traintestsplit = 0.2, batch_size=200)
     42 
     43 # Generate Testing Data

/content/function_dnn_powercontrol.py in train(X, Y, location, training_epochs, batch_size, LR, n_hidden_1, n_hidden_2, n_hidden_3, traintestsplit, LRdecay)
     65     X_train = np.transpose(X[:, 0:num_train])     # training data
     66     Y_train = np.transpose(Y[:, 0:num_train])
---> 67     x = tf.placeholder("float",None)
     68     y = tf.placeholder("float",None)
     69     is_train = tf.placeholder("bool")

AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by Haoran-S** [comment]
solved.
